CREATE TABLE IF NOT EXISTS public.quiz (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT(now()),
    updated_at timestamptz NOT NULL DEFAULT(now())
);