CREATE TABLE IF NOT EXISTS public.question (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rf_quiz_id BIGINT REFERENCES public.quiz(id),
    title TEXT NOT NULL,
    answer CHARACTER VARYING(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT(now()),
    updated_at timestamptz NOT NULL DEFAULT(now())
)